version: "3"

vars:
    MAIN_FILE: cmd/server/main.go
    BIN_DIR: bin
    BIN_NAME: server
    DATABASE_URL: postgres://deployease:deployease_password@localhost:5434/deployease_dev?sslmode=disable
    MIGRATIONS_DIR: sql/migrations

tasks:
    default:
        cmds:
            - task: help

    help:
        desc: Display available tasks
        silent: true
        cmds:
            - echo "DeployEase Backend"
            - echo "Available tasks:"
            - task -l

    # Development tasks
    dev:
        desc: Start development server
        cmds:
            - go run {{.MAIN_FILE}}

    # Build tasks
    build:
        desc: Build backend binary
        cmds:
            - mkdir -p {{.BIN_DIR}}
            - go build -o {{.BIN_DIR}}/{{.BIN_NAME}} {{.MAIN_FILE}}

    # Test tasks
    test:
        desc: Run all tests
        cmds:
            - go test ./...

    test:coverage:
        desc: Run tests with coverage
        cmds:
            - go test -coverprofile=coverage.out ./...
            - go tool cover -html=coverage.out

    # Database tasks
    db:goose:up:
        desc: Apply all pending goose migrations
        cmds:
            - goose -dir {{.MIGRATIONS_DIR}} postgres "{{.DATABASE_URL}}" up

    db:goose:down:
        desc: Rollback last goose migration
        cmds:
            - goose -dir {{.MIGRATIONS_DIR}} postgres "{{.DATABASE_URL}}" down

    db:goose:status:
        desc: Show current goose migration status
        cmds:
            - goose -dir {{.MIGRATIONS_DIR}} postgres "{{.DATABASE_URL}}" status

    db:goose:create:
        desc: Create a new goose SQL migration file
        cmds:
            - goose -dir {{.MIGRATIONS_DIR}} create {{.NAME}} sql

    db:seed:
        desc: Seed database with initial data
        cmds:
            - go run {{.MAIN_FILE}} seed

    # Code generation tasks
    sqlc:install:
        desc: Install sqlc if not already installed
        cmds:
            - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
        status:
            - command -v sqlc

    generate:
        desc: Run code generation
        deps:
            - sqlc:install
        cmds:
            - task: sqlc:generate
            - go generate ./...

    sqlc:generate:
        desc: Generate SQL code using sqlc
        deps:
            - sqlc:install
        cmds:
            - sqlc generate

    # Lint tasks
    lint:
        desc: Run linters
        cmds:
            - go vet ./...
            - golangci-lint run

    # Dependency tasks
    deps:
        desc: Download dependencies
        cmds:
            - go mod download

    deps:tidy:
        desc: Tidy dependencies
        cmds:
            - go mod tidy

    # Clean tasks
    clean:
        desc: Clean build artifacts
        cmds:
            - rm -rf {{.BIN_DIR}}
