// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hello.sql

package db

import (
	"context"
)

const getGreeting = `-- name: GetGreeting :one
SELECT 'Hello, world!' AS greeting
`

func (q *Queries) GetGreeting(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getGreeting)
	var greeting string
	err := row.Scan(&greeting)
	return greeting, err
}
